### ISSUE TITLE
Package manager? 

### ISSUE THREAD

**Issue by staberas** [ikruusa/lichee_dock_images#1]
Is it possible to include a package manager? or at least a package installer?

**Comment by ikruusa** [comment]
Hi! Could you please be more specific? At the heart this linux system is built from scratch (generated by buildroot). There is no relation to any distro.

**Comment by staberas** [comment]
i actually wanted to add some specific python modules which requires me to have pip which requires apt-get or at worst i have a  deb installer avaiable. while your image is light my specific case requires me to install some extra stuff. Anyway i managed to got the Ubuntu image running my sd card was bad but your image was the only one that worked on it for some reason.
